name: End-to-end tests

on:
  push:

jobs:
  vars:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEFAULT_REGION: eu-west-1
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET: ${{ secrets.BUCKET }}
      BUCKET_KEY: ${{ secrets.BUCKET_KEY }}
      RESIZED_BUCKET: ${{ secrets.RESIZED_BUCKET }}
      TABLE_NAME: ${{ secrets.TABLE_NAME }}
    steps:
      - name: "echo env vars"
        run:
          echo "Here -> ${{secrets.BUCKET}} ${{secrets.TABLE_NAME}}" Here ->
          ${{secrets.AWS_DEFAULT_REGION} The job_id is $GITHUB_JOB The id of
          this action is $GITHUB_ACTION The run id is $GITHUB_RUN_ID The GitHub
          Actor's username is $GITHUB_ACTOR"
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: check github context
        run: echo "$GITHUB_CONTEXT"

      - name: Test enviroment variables
        run: |
          echo AWS_DEFAULT_REGION
          echo ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Run end-to-end tests
        run: npx tsx e2e-tests/index.ts
