name: End-to-end tests

on:
  push:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET: ${{ secrets.BUCKET }}
  BUCKET_KEY: ${{ secrets.BUCKET_KEY }}
  RESIZED_BUCKET: ${{ secrets.RESIZED_BUCKET }}
  TABLE_NAME: ${{ secrets.TABLE_NAME }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: check github context
        run: echo "$GITHUB_CONTEXT"

      - name: Test env variables
        run: |
          echo AWS_DEFAULT_REGION
          echo ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Check region
        run: |
          if ${{ secrets.AWS_DEFAULT_REGION }} == 'eu-west-1'
            echo ${{ secrets.AWS_DEFAULT_REGION }}
          fi

      - name: Run end-to-end tests
        run: npx tsx e2e-tests/index.ts
