name: End-to-end tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET: ${{ secrets.BUCKET }}
      BUCKET_KEY: ${{ secrets.BUCKET_KEY }}
      RESIZED_BUCKET: ${{ secrets.RESIZED_BUCKET }}
      TABLE_NAME: ${{ secrets.TABLE_NAME }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: check github context
        run: echo "$GITHUB_CONTEXT"

      - name: Test env variables
        run: |
          echo AWS_DEFAULT_REGION
          echo ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Check AWS_DEFAULT_REGION
        run: |
          if [ ${{ secrets.AWS_DEFAULT_REGION }} == 'eu-west-1' ] ; then
            echo " AWS_DEFAULT_REGION is eu-west-1"
          fi

      - name: Check AWS_REGION
        run: |
          if [ ${{ secrets.AWS_REGION }} == 'eu-west-1' ] ; then
            echo " AWS_REGION is eu-west-1"
          fi

      - name: Check validation region is working
        run: |
          if [ ${{ secrets.AWS_DEFAULT_REGION }} == 'mauro' ] ; then
            echo " region is mauro"
          fi

      - name: Run end-to-end tests
        run: npx tsx e2e-tests/index.ts
